### ISSUE TITLE
Newest Land card gets cut in half on laptop screen size

### ISSUE THREAD

**Issue by Sm00g15** [decentraland/marketplace#535] opened 2018-10-08 21:23 UTC
![screen shot 2018-10-09 at 10 22 54 am](https://user-images.githubusercontent.com/14209806/46634429-6b03ec00-cbad-11e8-9acd-f434e983b5fe.jpg)

**Comment by abarmat** [comment] 2018-11-01 15:33
Hey thank you for reporting this problem. 

There is an upcoming revamp of the Marketplace UI that you can follow at https://github.com/decentraland/marketplace/projects/9

We are fixing this along with some other issues.

**Comment by nicosantangelo** [comment] 2019-04-03 10:35
Hey, I'm closing this because it's working as intended (via horizontal scroll) and because it's likely to change.

Thanks for the report!

**Closed by nicosantangelo** 2019-04-03 10:35 UTC
Labels: bug
